### ISSUE TITLE
Syntex error on line 33

### ISSUE THREAD

**Issue by cinetube** [paolo9785/rpi_lamp_install_script#1]
Getting Syntex error on line 33

./install.sh: line 33: syntax error near unexpected token `('
./install.sh: line 33: `PORT_CHECK = (sudo lsof -nPi | grep ":80 (LISTEN)" | wc -l)'

error image attached

![SNAG-0000](https://user-images.githubusercontent.com/23441775/68168135-fce94e80-ff91-11e9-8504-17eaab186b48.jpg)

**Comment by paolo9785** [comment]
thanks for reporting. syntax error fixed.
